name: Java CI on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test with Maven
        run: mvn clean test

      - name: Publish JUnit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/

      - name: Publish Test Report to GitHub UI
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Results
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
